name: Build Typst document
on: 
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: checkout fonts repo
        uses: actions/checkout@v4
        with:
          repository: ckunte/fonts
          path: fonts

      - name: prep typst
        uses: typst-community/setup-typst@v3
      - run: typst compile structural-dynamics.typ --font-path=fonts
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            structural-dynamics.pdf
